const COURSE = {
  code: 'IT3226',
  title: 'Cloud Computing',
  description: 'Design, deployment and management of cloud-based applications and infrastructure on Amazon Web Services.',
  aus: '4 Academic Units',
  prerequisites: 'IT2301 Networking Fundamentals or IT2305 Systems Administration',
  schedule: 'Tuesday & Thursday, 9:00 am – 11:00 am',
  venue: 'IT Lab 3, Block L',
};

const INSTRUCTOR = {
  name: 'Mr. Guanming Qiao',
  initials: 'GQ',
  email: 'guanmingqiao@nyp.edu.sg',
  officeHours: 'Wednesday 2:00 pm – 4:00 pm, Room L4-05',
  title: 'Lecturer, School of Information Technology',
  bio: 'Specialising in cloud infrastructure, DevOps practices, and distributed systems. Research interests include infrastructure-as-code, automated deployment pipelines, and cloud-native architecture patterns.',
};

const MODULES = [
  {
    week: 1,
    name: 'Introduction to Cloud Computing',
    desc: 'Cloud computing fundamentals, service models, and the AWS global infrastructure.',
    overview: 'Cloud computing has fundamentally changed how organisations design, deploy and scale software. In this opening week we establish the conceptual foundations — what cloud computing is, why it matters, and how AWS structures its global infrastructure. You will leave with a clear mental model for comparing cloud approaches and an account ready for the labs ahead.',
    objectives: [
      'Define the three cloud service models (IaaS, PaaS, SaaS) and give real-world examples of each.',
      'Describe the AWS global infrastructure: Regions, Availability Zones, and Edge Locations.',
      'Contrast on-premises, hybrid, and fully cloud-hosted deployment models.',
      'Apply the AWS Shared Responsibility Model to determine what you own versus what AWS owns.',
    ],
    topics: [
      { name: 'Cloud service models', detail: 'IaaS, PaaS, SaaS — characteristics and examples' },
      { name: 'Deployment models', detail: 'Public, private, hybrid cloud trade-offs' },
      { name: 'AWS Global Infrastructure', detail: 'Regions, AZs, Local Zones, Edge Locations' },
      { name: 'Shared Responsibility Model', detail: 'Security of vs. security in the cloud' },
      { name: 'AWS Free Tier', detail: 'What is included and how to avoid surprise bills' },
    ],
    studyHours: 4,
  },
  {
    week: 2,
    name: 'AWS Core Services: EC2 & VPC',
    desc: 'Launching instances, networking, security groups, Elastic IPs, and VPC design.',
    overview: 'Elastic Compute Cloud (EC2) is the backbone of most AWS architectures. This week you learn to provision, connect to, and manage EC2 instances, then situate them inside a Virtual Private Cloud with appropriate networking. You will understand how subnets, route tables, and security groups collectively control who can communicate with your instances.',
    objectives: [
      'Launch, connect to, and terminate EC2 instances of appropriate types and sizes.',
      'Design a VPC with public and private subnets across multiple Availability Zones.',
      'Configure Security Groups and Network ACLs to enforce least-privilege network access.',
      'Attach an Elastic IP to maintain a stable public address for a running instance.',
    ],
    topics: [
      { name: 'EC2 instance types', detail: 'General purpose, compute, memory, storage-optimised families' },
      { name: 'AMIs and key pairs', detail: 'Launching from AMIs, SSH authentication' },
      { name: 'VPC fundamentals', detail: 'CIDR blocks, subnets, route tables, Internet Gateway' },
      { name: 'Security Groups', detail: 'Stateful inbound/outbound rules, best practices' },
      { name: 'Network ACLs', detail: 'Stateless subnet-level control, rule evaluation order' },
      { name: 'Elastic IPs', detail: 'Static public addresses, association and release' },
    ],
    studyHours: 5,
  },
  {
    week: 3,
    name: 'Storage: S3 & EBS',
    desc: 'Object storage, bucket policies, lifecycle rules, versioning, and block storage.',
    overview: 'AWS offers storage at multiple levels of abstraction. S3 provides virtually unlimited object storage with fine-grained access control; EBS provides persistent block storage attached directly to EC2 instances. Understanding when to use each — and how to configure them securely — is a foundational cloud skill.',
    objectives: [
      'Create and configure S3 buckets with appropriate permissions and bucket policies.',
      'Enable versioning and configure lifecycle rules to manage object retention and cost.',
      'Host a static website directly from an S3 bucket.',
      'Attach, format, and mount EBS volumes to EC2 instances.',
    ],
    topics: [
      { name: 'S3 storage classes', detail: 'Standard, IA, Glacier, Intelligent-Tiering — cost trade-offs' },
      { name: 'Bucket policies & ACLs', detail: 'JSON policy syntax, public access blocks' },
      { name: 'Versioning & lifecycle', detail: 'Protecting against accidental deletion, automated tiering' },
      { name: 'S3 static website hosting', detail: 'Index/error documents, CORS configuration' },
      { name: 'EBS volume types', detail: 'gp3, io2, sc1 — IOPS vs. throughput vs. cost' },
      { name: 'Snapshots', detail: 'Point-in-time backups, cross-region copy' },
    ],
    studyHours: 4,
  },
  {
    week: 4,
    name: 'Identity & Access Management',
    desc: 'Users, groups, roles, policies, and the principle of least privilege.',
    overview: 'IAM is arguably the most critical AWS service: misconfigured permissions are a leading cause of cloud security incidents. This week covers the full IAM model and drills the principle of least privilege so deeply it becomes second nature. You will also learn how EC2 instances and Lambda functions acquire permissions without embedding long-lived credentials.',
    objectives: [
      'Design and write IAM policies that grant precisely the permissions needed — no more.',
      'Differentiate managed policies from inline policies and explain when to use each.',
      'Create IAM roles and attach them to EC2 instances via instance profiles.',
      'Use the IAM Policy Simulator to verify permissions before deploying changes.',
    ],
    topics: [
      { name: 'IAM principals', detail: 'Users, groups, roles — identity vs. principal' },
      { name: 'Policy types', detail: 'Identity-based, resource-based, permission boundaries' },
      { name: 'Policy JSON anatomy', detail: 'Effect, Action, Resource, Condition elements' },
      { name: 'Instance profiles', detail: 'How EC2 obtains temporary credentials via IMDS' },
      { name: 'STS and AssumeRole', detail: 'Cross-account access, temporary credentials' },
      { name: 'IAM best practices', detail: 'MFA, access key rotation, root account lockdown' },
    ],
    studyHours: 5,
  },
  {
    week: 5,
    name: 'Databases in the Cloud',
    desc: 'RDS, DynamoDB, and choosing the right database for your workload.',
    overview: 'AWS offers purpose-built database services for relational, key-value, document, and time-series data. This week focuses on the two most widely used: RDS for relational workloads requiring SQL, and DynamoDB for high-throughput, low-latency NoSQL access patterns. You will learn to make the right choice based on consistency requirements, query patterns, and scale.',
    objectives: [
      'Deploy a Multi-AZ RDS instance and explain the automatic failover mechanism.',
      'Create read replicas and describe when they improve read performance.',
      'Design a DynamoDB table with an appropriate partition key and sort key.',
      'Choose between RDS and DynamoDB given a set of workload requirements.',
    ],
    topics: [
      { name: 'RDS engine options', detail: 'MySQL, PostgreSQL, Aurora — when to use each' },
      { name: 'Multi-AZ & Read Replicas', detail: 'High availability vs. read scaling' },
      { name: 'DynamoDB data model', detail: 'Tables, items, attributes, partition and sort keys' },
      { name: 'Global Secondary Indexes', detail: 'Alternate access patterns without full scans' },
      { name: 'DynamoDB capacity modes', detail: 'On-demand vs. provisioned, auto-scaling' },
      { name: 'Database security', detail: 'VPC placement, encryption at rest, parameter groups' },
    ],
    studyHours: 5,
  },
  {
    week: 6,
    name: 'Serverless: Lambda & API Gateway',
    desc: 'Event-driven architecture, function deployment, and managed REST API creation.',
    overview: 'Serverless does not mean "no servers" — it means you do not manage them. AWS Lambda runs your code in response to events without provisioning or scaling infrastructure. Combined with API Gateway, you can build fully managed REST APIs that scale automatically. This week introduces event-driven thinking and the operational model of serverless systems.',
    objectives: [
      'Write, deploy, and test Lambda functions triggered by S3, DynamoDB, and HTTP events.',
      'Explain cold starts, execution environments, and strategies to minimise latency.',
      'Create a REST API in API Gateway and integrate it with Lambda functions.',
      'Design an event-driven workflow using Lambda and Amazon EventBridge.',
    ],
    topics: [
      { name: 'Lambda fundamentals', detail: 'Runtimes, handler, context, environment variables' },
      { name: 'Triggers and event sources', detail: 'S3, DynamoDB Streams, SQS, API Gateway, EventBridge' },
      { name: 'Lambda layers', detail: 'Sharing dependencies and custom runtimes' },
      { name: 'Cold starts', detail: 'Causes, measurement, mitigation strategies' },
      { name: 'API Gateway', detail: 'REST vs. HTTP API, resources, methods, deployment stages' },
      { name: 'Event-driven patterns', detail: 'Fan-out, choreography vs. orchestration' },
    ],
    studyHours: 5,
  },
  {
    week: 7,
    name: 'Containers & Orchestration',
    desc: 'Docker on AWS, ECS task definitions, Fargate, and an introduction to EKS.',
    overview: 'Containers package applications with their dependencies, making deployments consistent and portable. AWS provides managed services — ECS and EKS — to orchestrate containers at scale. This week begins with Docker fundamentals and progresses through ECS to a conceptual overview of Kubernetes on AWS.',
    objectives: [
      'Build and push a Docker image to Amazon ECR.',
      'Define ECS task definitions and deploy a service on Fargate.',
      'Compare ECS Fargate and ECS on EC2 launch types and select appropriately.',
      'Describe the Kubernetes control plane and worker node architecture at a conceptual level.',
    ],
    topics: [
      { name: 'Docker fundamentals', detail: 'Images, containers, Dockerfile, layer caching' },
      { name: 'Amazon ECR', detail: 'Pushing, pulling, lifecycle policies, image scanning' },
      { name: 'ECS task definitions', detail: 'CPU/memory, port mappings, environment variables' },
      { name: 'ECS services', detail: 'Desired count, deployment strategies, load balancing integration' },
      { name: 'Fargate vs. EC2 launch type', detail: 'Cost, control, and operational overhead' },
      { name: 'EKS overview', detail: 'Kubernetes concepts: pods, deployments, services, ingress' },
    ],
    studyHours: 6,
  },
  {
    week: 8,
    name: 'CI/CD on AWS',
    desc: 'GitHub Actions, OIDC authentication, SSM deployments, and Terraform basics.',
    overview: 'Continuous Integration and Continuous Delivery transform how teams ship software — from manual, error-prone deployments to automated, auditable pipelines. This week you build a complete CI/CD pipeline: code pushed to GitHub triggers a workflow that tests, builds, and deploys to EC2. You will also write your first Terraform configuration to manage infrastructure as code.',
    objectives: [
      'Build a GitHub Actions workflow that deploys to EC2 on every push to main.',
      'Use OIDC to authenticate GitHub Actions to AWS without storing long-lived secrets.',
      'Execute remote commands on EC2 via AWS Systems Manager without opening port 22.',
      'Write Terraform configuration to provision and manage AWS resources reproducibly.',
    ],
    topics: [
      { name: 'GitHub Actions', detail: 'Workflows, jobs, steps, runners, secrets management' },
      { name: 'OIDC authentication', detail: 'Federated identity, eliminating long-lived access keys' },
      { name: 'SSM Run Command', detail: 'Remote execution without SSH, full CloudTrail audit trail' },
      { name: 'Terraform basics', detail: 'Providers, resources, state, plan/apply lifecycle' },
      { name: 'Infrastructure as Code', detail: 'Idempotency, drift detection, version control for infra' },
      { name: 'Deployment strategies', detail: 'In-place, blue/green, canary — trade-offs and use cases' },
    ],
    studyHours: 6,
  },
  {
    week: 9,
    name: 'Monitoring & Observability',
    desc: 'CloudWatch metrics, logs, alarms, Log Insights, and X-Ray distributed tracing.',
    overview: 'You cannot manage what you cannot see. Observability — the ability to understand a system\'s internal state from its external outputs — is as important as the system itself. This week covers the AWS observability stack: CloudWatch for metrics and logs, X-Ray for distributed tracing, and AWS Config for resource compliance.',
    objectives: [
      'Create CloudWatch dashboards combining metrics from multiple AWS services.',
      'Set CloudWatch alarms that trigger Auto Scaling actions or SNS notifications.',
      'Query application logs using CloudWatch Log Insights.',
      'Instrument a Lambda function with X-Ray and analyse a service map.',
    ],
    topics: [
      { name: 'CloudWatch metrics', detail: 'Namespaces, dimensions, statistics, custom metrics' },
      { name: 'CloudWatch alarms', detail: 'Thresholds, alarm actions, composite alarms' },
      { name: 'CloudWatch Logs', detail: 'Log groups, log streams, metric filters, retention policies' },
      { name: 'Log Insights', detail: 'Query syntax, common patterns, visualisation' },
      { name: 'AWS X-Ray', detail: 'Segments, subsegments, annotations, service maps' },
      { name: 'AWS Config', detail: 'Resource inventory, compliance rules, auto-remediation' },
    ],
    studyHours: 4,
  },
  {
    week: 10,
    name: 'Security & Compliance',
    desc: 'KMS encryption, AWS WAF, GuardDuty, Security Hub, and compliance frameworks.',
    overview: 'Security in the cloud is a shared responsibility — and your half matters enormously. This week covers defence-in-depth: encrypting data at rest and in transit, detecting threats with GuardDuty, blocking malicious traffic with WAF, and aggregating findings in Security Hub. We also discuss how frameworks such as MAS TRM and ISO 27001 map to AWS controls.',
    objectives: [
      'Encrypt S3 objects and EBS volumes using AWS KMS customer-managed keys.',
      'Configure AWS WAF rules to block common web exploits (SQLi, XSS).',
      'Interpret GuardDuty findings and outline a structured remediation workflow.',
      'Map Security Hub findings to a compliance standard such as CIS AWS Foundations.',
    ],
    topics: [
      { name: 'KMS', detail: 'CMKs, data keys, envelope encryption, key policies' },
      { name: 'ACM', detail: 'TLS certificates, auto-renewal, integration with ALB and CloudFront' },
      { name: 'AWS WAF', detail: 'Web ACLs, managed rule groups, rate-based rules' },
      { name: 'GuardDuty', detail: 'Threat intelligence, anomaly detection, finding types' },
      { name: 'Security Hub', detail: 'Aggregated findings, compliance standards, integrations' },
      { name: 'MAS TRM & Cloud', detail: 'Singapore financial sector requirements and AWS alignment' },
    ],
    studyHours: 5,
  },
  {
    week: 11,
    name: 'Cost Optimisation',
    desc: 'Pricing models, Cost Explorer, right-sizing, Savings Plans, and Trusted Advisor.',
    overview: 'Cloud costs can spiral quickly if not managed deliberately. This week you learn to read and act on your AWS bill, choose the right pricing model for each workload, and use AWS-native tools to identify waste. The goal is not to minimise spend at all costs, but to maximise value — spending the right amount on the right resources at the right time.',
    objectives: [
      'Navigate Cost Explorer to identify cost drivers and usage trends over time.',
      'Compare on-demand, Reserved Instance, Savings Plan, and Spot pricing models.',
      'Use AWS Compute Optimizer recommendations to right-size EC2 instances.',
      'Set up AWS Budgets with email alerts to prevent unexpected overspend.',
    ],
    topics: [
      { name: 'AWS pricing fundamentals', detail: 'Compute, storage, and data transfer cost components' },
      { name: 'Pricing models', detail: 'On-demand, Reserved Instances, Savings Plans, Spot instances' },
      { name: 'Cost Explorer', detail: 'Filters, grouping, forecasting, rightsizing recommendations' },
      { name: 'AWS Budgets', detail: 'Cost, usage, and reservation budgets with threshold alerts' },
      { name: 'Compute Optimizer', detail: 'ML-based instance right-sizing recommendations' },
      { name: 'Trusted Advisor', detail: 'Cost, performance, security, fault tolerance checks' },
    ],
    studyHours: 4,
  },
  {
    week: 12,
    name: 'Capstone Project',
    desc: 'Design and deploy a cloud-native application applying concepts from the full course.',
    overview: 'The capstone integrates everything you have learned. Working in groups of 3–4, you will architect, build, and deploy a cloud-native web application on AWS — complete with a CI/CD pipeline, CloudWatch monitoring dashboard, IAM least-privilege configuration, and a cost estimate. Each group presents their system and defends their architectural decisions to the class.',
    objectives: [
      'Architect a multi-tier application applying the five pillars of the AWS Well-Architected Framework.',
      'Implement a CI/CD pipeline that deploys automatically on push to the main branch.',
      'Configure CloudWatch monitoring with meaningful alarms and a group dashboard.',
      'Present and justify architectural decisions to peers and the instructor.',
    ],
    topics: [
      { name: 'AWS Well-Architected Framework', detail: 'Reliability, security, efficiency, cost, operational excellence' },
      { name: 'Architecture design patterns', detail: 'Multi-tier, loosely coupled, managed services preference' },
      { name: 'Project lab sessions', detail: 'Guided build time with instructor and TA support' },
      { name: 'Group presentations', detail: 'System demo, architecture walkthrough, lessons learned' },
    ],
    studyHours: 12,
  },
];

const LABS = [
  {
    id: 1,
    title: 'Setting Up Your AWS Environment',
    shortDesc: 'Configure the AWS CLI, create a least-privilege IAM user, enable MFA, and set up billing alerts.',
    duration: '90 min',
    difficulty: 'Beginner',
    prerequisiteWeeks: [1, 4],
    services: ['IAM', 'CloudWatch Billing', 'AWS CLI'],
    overview: 'A correctly configured AWS account is the foundation for everything that follows. In this lab you create a dedicated IAM user for day-to-day work (root credentials must never be used for operations), configure the AWS CLI on your machine, enable MFA, and set a billing alarm so you are notified if your usage unexpectedly exceeds the free tier.',
    steps: [
      { title: 'Lock down the root account', detail: 'Enable MFA on the root account using a virtual authenticator app. Delete any root access keys if they exist.' },
      { title: 'Create an IAM admin user', detail: 'Create a user in the Administrators group, grant console access, and download the access key credentials CSV.' },
      { title: 'Configure the AWS CLI', detail: 'Run aws configure with your access key, secret key, region ap-southeast-1, and output format json.' },
      { title: 'Set a billing alarm', detail: 'Create a CloudWatch billing alarm that sends an SNS email notification when estimated charges exceed $5 USD.' },
      { title: 'Verify access', detail: 'Run aws sts get-caller-identity and aws s3 ls to confirm your CLI credentials are working correctly.' },
    ],
  },
  {
    id: 2,
    title: 'Launching and Connecting to EC2',
    shortDesc: 'Provision a VPC, launch an EC2 instance, install nginx, and serve a webpage to the internet.',
    duration: '2 hours',
    difficulty: 'Beginner',
    prerequisiteWeeks: [2],
    services: ['EC2', 'VPC', 'Security Groups', 'Elastic IP'],
    overview: 'In this lab you build the foundational cloud compute setup: a VPC with a public subnet, an EC2 instance running nginx, and an Elastic IP for a stable address. You will practise writing Security Group rules to allow only the specific traffic your instance needs — the practical application of least-privilege networking.',
    steps: [
      { title: 'Create a VPC and public subnet', detail: 'Create a VPC with CIDR 10.0.0.0/16, add a public subnet 10.0.1.0/24, and attach an Internet Gateway with a route from 0.0.0.0/0.' },
      { title: 'Configure a Security Group', detail: 'Allow inbound TCP 80 (HTTP) from 0.0.0.0/0 and TCP 22 (SSH) from your IP address only. Allow all outbound.' },
      { title: 'Launch an EC2 instance', detail: 'Launch Amazon Linux 2023, t2.micro, into your public subnet with your new security group. Generate and download a key pair.' },
      { title: 'Connect and install nginx', detail: 'SSH into the instance using your key pair. Run: sudo dnf install nginx -y && sudo systemctl enable --now nginx.' },
      { title: 'Allocate an Elastic IP', detail: 'Allocate an EIP in the console and associate it to your instance. Open the IP in your browser — you should see the nginx welcome page.' },
    ],
  },
  {
    id: 3,
    title: 'S3 Static Website Hosting',
    shortDesc: 'Host a static website on S3, write a bucket policy for public access, and optionally front with CloudFront.',
    duration: '90 min',
    difficulty: 'Beginner',
    prerequisiteWeeks: [3],
    services: ['S3', 'IAM', 'CloudFront'],
    overview: 'S3 can host a fully functional static website at very low cost — no server required. In this lab you upload a static site to an S3 bucket, configure it for website hosting, write a bucket policy to allow public reads, and optionally front it with CloudFront for HTTPS support and global edge caching.',
    steps: [
      { title: 'Create and configure the bucket', detail: 'Create a bucket in ap-southeast-1. Under Block Public Access, disable "Block all public access" specifically for this website bucket.' },
      { title: 'Enable static website hosting', detail: 'In Bucket properties → Static website hosting, enable it and set index.html as the index document and error.html as the error document.' },
      { title: 'Upload your website files', detail: 'Upload index.html and any assets via the console or CLI. Set appropriate content-type metadata for each file type.' },
      { title: 'Write a public read bucket policy', detail: 'Attach a bucket policy granting s3:GetObject to Principal "*" on all objects (arn:aws:s3:::your-bucket/*) in the bucket.' },
      { title: 'Test and add CloudFront (optional)', detail: 'Access the S3 website endpoint in your browser. Optionally create a CloudFront distribution with your bucket as origin for HTTPS and global caching.' },
    ],
  },
  {
    id: 4,
    title: 'IAM Roles and Policies',
    shortDesc: 'Write least-privilege policies, attach roles to EC2 instances, and verify with the Policy Simulator.',
    duration: '2 hours',
    difficulty: 'Intermediate',
    prerequisiteWeeks: [4],
    services: ['IAM', 'EC2', 'S3', 'IAM Policy Simulator'],
    overview: 'IAM policy writing takes practice. In this lab you work through a series of scenarios — granting an EC2 instance read access to a specific S3 bucket, restricting API calls to ap-southeast-1 only, and denying dangerous actions with explicit Deny statements. For each scenario you write the policy JSON, test it in the Policy Simulator, then verify with the AWS CLI.',
    steps: [
      { title: 'Write a scoped S3 read-only policy', detail: 'Create an inline policy granting s3:GetObject and s3:ListBucket on a specific bucket ARN only — not *.' },
      { title: 'Create an EC2 instance role', detail: 'Create an IAM role with EC2 as the trusted service. Attach your S3 policy. Launch a new EC2 instance with this role as its instance profile.' },
      { title: 'Verify access from the instance', detail: 'SSH in and run aws s3 ls s3://your-bucket (should succeed) and aws s3 ls s3://another-bucket (should be Access Denied).' },
      { title: 'Test in the Policy Simulator', detail: 'Open the IAM Policy Simulator, select your EC2 role, and simulate s3:DeleteObject — confirm the result is "denied".' },
      { title: 'Add a region-lock condition', detail: 'Add a Deny statement with a Condition on aws:RequestedRegion to restrict all API calls to ap-southeast-1 only. Test with the CLI.' },
    ],
  },
  {
    id: 5,
    title: 'CI/CD with GitHub Actions',
    shortDesc: 'Build a full deployment pipeline — push to GitHub, authenticate via OIDC, deploy to EC2 via SSM. No SSH keys stored.',
    duration: '3 hours',
    difficulty: 'Intermediate',
    prerequisiteWeeks: [4, 8],
    services: ['EC2', 'IAM', 'SSM', 'SSM Parameter Store', 'GitHub Actions'],
    overview: 'This is the culminating lab. You will wire together everything from the course into a working CI/CD pipeline. When you push to the main branch of your GitHub repository, a GitHub Actions workflow authenticates to AWS using OIDC (no access keys stored in GitHub), executes a deployment command on your EC2 instance via SSM Run Command, and reports the result. You will also see how config changes in SSM Parameter Store update the live site without triggering a redeploy.',
    steps: [
      { title: 'Register the GitHub OIDC provider', detail: 'In IAM → Identity Providers, create an OIDC provider for token.actions.githubusercontent.com with audience sts.amazonaws.com.' },
      { title: 'Create the GitHub Actions IAM role', detail: 'Create a role with a trust policy allowing your specific repo to assume it. Attach permissions for ssm:SendCommand and ssm:PutParameter.' },
      { title: 'Prepare the EC2 instance', detail: 'Ensure SSM Agent is running and your instance has an instance profile with AmazonSSMManagedInstanceCore attached.' },
      { title: 'Write the deploy workflow', detail: 'Create .github/workflows/deploy.yml. It authenticates via OIDC with aws-actions/configure-aws-credentials, then calls aws ssm send-command to pull the latest code.' },
      { title: 'Demo a config-only update', detail: 'Edit config/app-config.json (change the announcement), push, and watch the separate sync-config workflow update SSM Parameter Store — live update with no EC2 deployment.' },
    ],
  },
];
